require 'cocoapods'
require 'cocoapods-flutter/native/specification/dsl'
require 'cocoapods-flutter/native/specification/set'
require 'cocoapods-flutter/native/specification/consumer'
require 'cocoapods-flutter/native/podfile'
require 'cocoapods-flutter/native/pod_source_preparer'
require 'cocoapods-flutter/native/archive/archive'
require 'cocoapods-flutter/native/archive/command_runner'